### ISSUE TITLE
Schema $ref Instead of Swagger Reference Object?

### ISSUE THREAD

**Issue by Smolations** [swagger-api/swagger-spec#284]
For the swagger Schema Object, there is a $ref property included. This confuses me because, if there is a $ref, what is the point in specifying the other properties? Will they override already-defined properties in the schema $ref? (this may be a question for the JSON spec folks...)

Also, looking at the Parameter object, the first example shows:
```
{
  "name": "user",
  "in": "body",
  "description": "user to add to the system",
  "required": true,
  "schema": {
    "$ref": "#/definitions/User"
  }
}
```

The Parameter Object spec says that the "schema" key should be associated with a Schema Object. However, the object associated with that key in the example looks exactly like a Reference Object. So, shouldn't the spec be updated to say that the "schema" key accepts `Schema Object|Reference Object`? What am I missing?

**P.S.** I LOVE what you guys are doing here. Great work!

**Comment by Smolations** [comment]
I have been working on a custom swagger implementation for my company's app to produce swagger documentation. As such, I have kept the swagger spec page open in a browser tab for weeks. I had _just_ refreshed the page and saw all of the examples, which triggered this issue post. Anyway, looking at more of the examples, as well as the schema.json in this project, it seems that there are many keys which could also accept a Reference Object instead of a full object of another type. So, my original question about adding a Reference Object as an alternative to the specified object should be considered for ALL object specs which could be associated with a Reference Object.  =]

**Comment by mohsen1** [comment]
Please read [this document](http://json-schema.org/example2.html) to learn more about JSON Schema's `$ref` keyword mechanism. What it really does, is replacing the object it's hosted on with destination of where it's value is pointing to

**Comment by webron** [comment]
@Smolations - The `Schema Object` is an extended subset of the JSON Schema. We don't support all JSON Schema properties, but we added a few of ours own.

`$ref` specifically is a valid property within JSON Schema and is indeed a [JSON Reference](http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03). If you look at the `Syntax` section in its spec, you will see that other properties within the object containing the reference SHALL be ignored. This means that if you do end up using it, parsers are expected to ignore all other properties within that object and as such there are no conflicts.

Since it's part of the `Schema Object` itself, there's no need to define it as `Schema Object|Reference Object` as it is contained in it.

**Comment by Smolations** [comment]
Thanks for the feedback, guys!  :+1:

**Comment by webron** [comment]
Closing this for now, please reopen if still an issue.
