### ISSUE TITLE
Security Requirements Object Contradiction

### ISSUE THREAD

**Issue by mikestanley** [swagger-api/swagger-spec#287]
In the Swagger Object descriptions and the Operation Descriptions, the field security states that "The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements)."

The Security Requirements Object however, states that "Lists the required security schemes to execute this operation. The object can have multiple security schemes declared in it which are all required (that is, there is a logical AND between the schemes)."

where security requirements object is:
{name}: [ ]

by the sound of it, I think it would work like:

primary: ["api_key"]
two_factor: ["password", "pin"]

where "api_key", "password", and "pin" reference security schemes.   

However, the examples and descriptions go on to say that name should map to the security scheme and that the array should be used for oauth scopes only, everyone else should have an empty array.

So this seems a bit contradictory to me.  Given the above, I don't understand how one could support:

1) a security requirement that allows "api_key" OR "password"
2) a security requirement that supports "password" AND "pin"

Additionally (but somewhat unrelated), I'm not sure I understand why security types are fixed to "basic", "api key" and "oauth".   This seems needlessly limiting (especially since other fields ^x- can be added to support additional configurations of other mechanisms).  How would one suggest something like "hmac" with a nonce?   where additional parameters and algorithms need to be communicated.  I suppose this could be wedged into api key with optional parameters for the nonce/etc. on all operations/paths.  But that doesn't seem appropriate.    Likewise, if we wanted to limit certain security types (like api_key and oauth) to https calls but allow something like "hmac" for unsecure channels (like passing an authorized secure/one-time-user/expiring link through an intermediary) to be less restrictive, it doesn't seem possible.   

Just starting to wrap my head around it so apologies if I missed something.  Thanks in advance.

**Comment by mikestanley** [comment]
i may have answered one of my own questions.  I see now that the swagger/operation security field is an array of security requirement objects, and that the security requirement object may have more than one key.  so to answer my question directly:

the OR case:
`security: [ { "api_key":[ ] }, {"password": [ ]} ]`

the AND case
`security: [ { "pin":[ ] , "password: []" } ]`

and combo ((password & pin) OR oauth):
`security: [ { "pin":[ ] , "password: []" }, {"oauth": ["read", "write"]} ]`

Is my understanding now correct?

I'm still interested in hearing the rationale behind limiting the security types to basic/api_key/oauth.  (were API key is a little misleading, it's more analogous to passing a credential/identifier in a "specified header").

**Comment by webron** [comment]
@mikestanley - Hi Mike, thanks for taking the time to write this up.

Regarding the AND/OR case, you got it right in your second comment, so I hope that's OK.

As for the security types - I believe this is more about tooling and the ability to automate support for security types. 

Before I get into that I'll say that the name `api_key` may be a bit misleading and it's basically any key/value combination that tends to appear either as a query parameter or a header (granted, cookies may be applicable as well). You can argue that `basic`is a specific case here, which is true, but the usage is probably common enough (not getting into whether that's good or not) to simplify documentation.

The specific types allow the supporting tools to automate the support for the security. If you look at swagger-ui, it has internal support for (most) OAuth2 flows, and we plan on integrating better support for basic/api_key and the possible combinations of them. The same goes for generated code using the code generator and I assume (and hope) that other tools out there take advantage of it as well.

There's a fine balance between extensibility and support for anything in such a spec, and security is not different in that sense. We could allow extension points in the various tools so that people could add support for all kinds of variances, but I think that Swagger 2.0 was mostly based on feedback gathered over the years since the initial spec was released and as part of the process it's not always easy to decide what to include and what not.

That said, we're always looking into the future trying to see what and where we can improve. Since this issue started as a collection of questions (which can most certainly continue to discuss), I'd invite you to open a 'clean' issue regarding the security definition restrictions and we could mark that as `Swagger.Next` for discussion.

**Comment by mikestanley** [comment]
@webron  thanks for the response.

I understand the benefits to tooling the restricted security options provide.  After I understood the AND/OR case, most (if not all) my current use cases are satisfied without issue, so the current options do strike a nice balance.   

I do think it's worth time considering, at the very least, how an hmac like security protocol could be achieved (with support for expiration and nonce parameters, as well as specification of a crypto algorithm).  this could be something that can be generalized and supported by tools as well.   It may be an edge case though so not sure it's worth the carry cost (making the case for more open extensions mechanism).   

I will mark this ticket as resolved and revisit opening a ticket about the restrictions on the security definitions.   I can happily live with those restrictions though for now.

**Comment by webron** [comment]
@mikestanley - Glad it's clearer now. Please make sure to open a ticket once you're ready. This is how the spec moves forward.
