### ISSUE TITLE
operationId: is it machine-first or people-first?

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-spec#423]
operationId, from the spec description: 
```
A friendly name for the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operation id to uniquely identify an operation.
```
When I see "friendly name" I think human-friendly, and that suggests I can use spaces. The Swagger schema declares it a string without any length restrictions, AFAICT. 

However, given that "it MAY be used by tools and libraries," that suggests it is a machine-friendly name first, especially that the attribute contains "ID" rather than "name".  

May I suggest either adding a pattern in the spec to restrict what characters can be used, and/or else consider adding a proper "name" field for operations. (NB: could use the summary field for that, but it's poorly named for that role, itself.)

**Comment by IvanGoncharov** [comment]
> However, given that "it MAY be used by tools and libraries," that suggests it is a machine-friendly name first, especially that the attribute contains "ID" rather than "name".

As I understand right now it used mostly in code generation tools for producing client and server side code. For example in `swagger-js` see [this](https://github.com/swagger-api/swagger-js#calling-an-api-with-swagger--the-browser) or in `swagger-codegen` see [this](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python3/PetApi.py#L33).

I totally agree with you that should be clarify in `swagger-spec` and additional restrictions should be enforced. Most reasonable is to limit this string to alphanumeric characters and it should always start with   letter. This is de facto standard for names in programming languages.

**Comment by earth2marsh** [comment]
:+1:

**Comment by webron** [comment]
Unfortunately, for 2.0, I'm going disagree with you. The text says MAY, not SHOULD, and there's a reason for it. We actually discussed imposing additional restrictions on the field. However, using it as an identified by machine is not as simple as it sounds. Different languages use different naming standards and sometimes permit different characters. We can, theoretically, restrict the the characters to the lowest known character subset, but that solves half the problem and we really didn't want to get into it. It is up to the tools to perform the processing of this field, should they choose to, and morph it to the standards they need, I don't see any problem removing spaces, as much as I don't see any problem changing character case style.

As for machine readable vs human readable, there have been requests to add it to the UI as a displayed field because some users use it to communicate specific operations between themselves. So, I don't know really. If it's machine readable only, it could just be a uuid 😉

We can reopen it for debate for the future version, of course, but we won't make everyone happy here.

**Comment by earth2marsh** [comment]
I don't disagree with those points. However, the "friendly name" is less precise than I'd like. How about:

`A string that uniquely identifies the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to restrict characters to a machine-friendly set.`

Not perfect, but a starting point!

**Comment by webron** [comment]
@earth2marsh I know I have an excuse for working today, what's yours? ;-) 

I'm OK with that change although I'd argue there's nothing non-machine-friendly in spaces. Sometimes a machine needs some space too.

**Comment by earth2marsh** [comment]
Is "my love for Swagger" too cheesy an answer? 

I think you're right to object to the similar imprecision about machine friendly. I'll make another pass and send a PR.

**Comment by webron** [comment]
Way, way too cheesy.
