### ISSUE TITLE
Scopes Object should be optional?

### ISSUE THREAD

**Issue by dwhieb** [swagger-api/swagger-spec#513]
The [Security Scheme Object](http://swagger.io/specification/#securitySchemeObject) lists the Scopes Object as required. However, the [OAuth 2.0 specification for the Access Token Scope](http://tools.ietf.org/html/rfc6749#section-3.3) allows the client to omit the scope parameter, as long as a default behavior is specified:

> If the client omits the scope parameter when requesting authorization, the authorization server MUST either process the request using a pre-defined default value or fail the request indicating an invalid scope. The authorization server SHOULD document its scope requirements and default value (if defined).

In [other places in the spec](http://tools.ietf.org/html/rfc6749#section-4.2.1), the scope parameter is explicitly stated as optional.

Does this mean that the Scopes Object should be optional too? Or allowed to be empty?

I'm wondering because I'm implementing an API with the Implicit grant flow where there's only one scope. Since there's just the one, I didn't want to have to declare it explicitly.

**Comment by webron** [comment]
You can leave it empty, but that means none is required.

**Comment by dwhieb** [comment]
Great - that's exactly what I was hoping for.

Follow-up question though: For the Security Requirement Object, the spec says:
> If the security scheme is of type "oauth2", then the value is a list of scope names required for the execution.

I assume the array can just be left empty too?

**Comment by webron** [comment]
Yup.

**Comment by dwhieb** [comment]
Awesome - thanks @webron!

**Comment by tedepstein** [comment]
@webron , would you mind reopening this issue? I'm submitting a PR to clarify that this usage is allowed. The spec is ambiguous or maybe misleading IMO, and we tripped over this in our implementation.

The [OAuth Flow Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#oauth-flow-object) says that the `scopes` map is REQUIRED, and doesn't specify any meaning for an empty object value. We took this to mean that `scopes` is required to be present AND non-empty, otherwise an empty value would seem to be circumventing the intention of the spec.

Likewise, [Security Requirement Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#securityRequirementObject) says:

> If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.

It doesn't _explicitly_ disallow an empty list for an OAuth security requirement, but taken in context, it's easy to assume, mistakenly, that the scopes array must be non-empty.

**Comment by webron** [comment]
@tedepstein that's fair for clarification, but there's no reason to reopen a ticket from 2015. I see you referenced the issue from the PR itself, and that should suffice.

**Comment by tedepstein** [comment]
@webron, OK.  :-)
